---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      # nodePort: 3000
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer