---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zephyr
  name: zephyr-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zephyr
  name: testresults-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi