---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chronograf
  name: chronograf
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: chronograf
  type: LoadBalancer